Add files via upload
Kentico/kontent-custom-element-samples pull request #110
Opened 2021-01-18 09:31 UTC by hzik

### Motivation

thumbnail for a custom element

2021-02-25 08:18 UTC, makma commented
> ### Motivation
> thumbnail for a custom element

?

2021-02-25 08:26 UTC, makma commented
Readme does not follow [requirements](https://github.com/Kentico/kontent-custom-element-samples#pull-request)

2021-02-25 08:27 UTC, makma requested changes
- readme does not follow [requirements](https://github.com/Kentico/kontent-custom-element-samples#pull-request)
- what is the motivation to have this element?
- index.html
-- fix formatting in regex.html
-- why using 3rd party jquery?

2021-06-07 12:16 UTC, strizr approved these changes

2021-06-07 12:19 UTC, merged